# Generated by Django 2.1.5 on 2019-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge_id', models.IntegerField()),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('capital', models.BooleanField()),
                ('lon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('no_accents', models.CharField(max_length=100)),
                ('alternative_names', models.CharField(max_length=100)),
                ('microregion', models.CharField(max_length=100)),
                ('mesoregion', models.CharField(max_length=100)),
            ],
        ),
    ]
