# Generated by Django 2.1.5 on 2019-02-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='ibge_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='uf',
            field=models.CharField(max_length=2),
        ),
    ]
